# Environment variables - PROD
environment: prod
azure_subscription_id: "00000000-0000-0000-0000-000000000003"
azure_resource_group: "rg-dataplatform-prod"
adf_instance_name: "adf-dataplatform-prod"
storage_account_name: "stadataplatformprod"
storage_container_source: "source-prod"
storage_container_sink: "sink-prod"
sql_server: "sql-dataplatform-prod.database.windows.net"
sql_database: "db-dataplatform-prod"
powerbi_workspace_id: "00000000-0000-0000-0000-000000000003"
log_level: "WARNING"
